#!/usr/bin/env python3
"""Fixed data sets of the weighted-estimation and selection parities (audit FR-11, wave 3).

Draws, with pyvinecopulib's own sampler (never ``pmcprg``), the samples that
``gen_pyvinecopulib_weighted.py``, ``gen_r_weighted.R`` and
``pmcprg/tests/test_parity_weighted.py`` all read, and writes them to

* ``pmcprg/tests/data/parity/weighted_data.csv`` — the weighted-estimation
  oracle: seven samples of n = 300 (Gaussian, Student, Clayton and its 90°
  rotation, Gumbel, Frank, BB1) with two weight vectors each, and one sample
  with heavy ties (the Gaussian one on an 8 × 8 grid) for the weighted-τ
  definitions;
* ``pmcprg/tests/data/parity/selection_data.csv`` — the recovery study:
  eight families at |τ| ≈ 0.4, n = 500, twenty seeds each.

**Everything is stored as integers**, so that R and Python read the same
doubles without trusting either's decimal parser: a coordinate is
``u = u_int / denom`` (a rank over ``n + 1``, or a tie level over 9), a
weight is ``w = w_int / 2**20`` — a division by a power of two, exact. The
generic weights are Beta(½, ½) draws (mass at both ends, as the ICE pair
posteriors ξ have), rounded to a multiple of 2⁻²⁰ and floored at 2⁻²⁰; the
{0, 1} weights keep each point with probability 0.6. Both are independent of
the data. Selection samples are stored as ``v_by_u``: the v-rank of the point
of u-rank i, i = 1 … n, so that ``u_i = i/(n + 1)`` and
``v_i = v_by_u[i]/(n + 1)``.

Usage, from the repository root (only to regenerate the data: the two
reference generators and the tests then need re-running)::

    .venv-parity/bin/python scripts/parity/gen_weighted_data.py
"""

from __future__ import annotations

import datetime
import platform
import re
import sys
from pathlib import Path

import numpy as np
import pyvinecopulib as pv

ROOT = Path(__file__).resolve().parents[2]
OUT_W = ROOT / "pmcprg" / "tests" / "data" / "parity" / "weighted_data.csv"
OUT_S = ROOT / "pmcprg" / "tests" / "data" / "parity" / "selection_data.csv"

W_SCALE = 2 ** 20     # generic weights are w_int / W_SCALE
TIE_LEVELS = 8        # the tie data set: 8 levels per margin, u = level / 9

# (dataset, family, rotation, par1, par2, seed). Parameters in the key of
# README.md (the unrotated family's θ or ρ; ν, δ as par2).
WEIGHTED = [
    ("gaussian",  "gaussian", 0,  0.6, None, 101),
    ("student",   "student",  0,  0.6, 5.0,  102),
    ("clayton",   "clayton",  0,  1.5, None, 103),
    ("clayton90", "clayton",  90, 1.5, None, 104),
    ("gumbel",    "gumbel",   0,  1.8, None, 105),
    ("frank",     "frank",    0,  5.0, None, 106),
    ("bb1",       "bb1",      0,  0.8, 1.4,  107),
]
N_WEIGHTED = 300

# The recovery study: |τ| ≈ 0.4 (0.39 to 0.41, see the τ column written).
SELECTION = [
    ("gaussian",  "gaussian", 0,  0.6,  None),
    ("student",   "student",  0,  0.6,  4.0),
    ("clayton",   "clayton",  0,  1.3,  None),
    ("clayton90", "clayton",  90, 1.3,  None),
    ("gumbel",    "gumbel",   0,  1.7,  None),
    ("frank",     "frank",    0,  4.2,  None),
    ("joe",       "joe",      0,  2.2,  None),
    ("bb1",       "bb1",      0,  0.5,  1.33),
]
N_SELECTION = 500
SEEDS_SELECTION = list(range(1, 21))


def bicop(family: str, rotation: int, par1: float, par2: float | None) -> pv.Bicop:
    pars = [par1] if par2 is None else [par1, par2]
    return pv.Bicop(family=getattr(pv.BicopFamily, family), rotation=rotation,
                    parameters=np.array(pars, dtype=float).reshape(-1, 1))


def ranks(x: np.ndarray) -> np.ndarray:
    """1-based ranks; the draws are continuous, a tie is an error."""
    if np.unique(x).size != x.size:
        sys.exit("tied draws: not continuous data")
    r = np.empty(x.size, dtype=np.int64)
    r[np.argsort(x, kind="stable")] = np.arange(1, x.size + 1)
    return r


def ints(a) -> str:
    return " ".join(str(int(x)) for x in a)


def header(what: str) -> list[str]:
    version = re.search(r'__version__\s*=\s*"([^"]+)"',
                        (ROOT / "pmcprg" / "__init__.py").read_text()).group(1)
    return [
        f"# {what} - generated by scripts/parity/gen_weighted_data.py; do not edit by hand.",
        f"# sampler: pyvinecopulib {pv.__version__} Bicop.sample(n, seeds=[seed]); numpy "
        f"{np.__version__}; Python {platform.python_version()} on {platform.platform()}",
        f"# generated {datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds')}"
        f", repository version {version}",
        "# command: .venv-parity/bin/python scripts/parity/gen_weighted_data.py",
    ]


def main() -> int:
    lines = header("FR-11 weighted-estimation data") + [
        "# u = u_int/denom, v = v_int/denom; generic weight w = w_gen/2^20 (Beta(1/2, 1/2),",
        "# rounded, >= 2^-20, numpy default_rng(seed + 1000)); w01 in {0, 1} (P(1) = 0.6, same rng).",
        "# gaussian_ties: the gaussian sample on an 8 x 8 grid (level = floor(8 r/(n+1)) + 1,",
        "# denom 9), with the gaussian weights. par2 is nu (student) or delta (bb1). tau: the",
        "# reference's tau of the generating parameters (pyvinecopulib Bicop.tau).",
        "dataset,family,rotation,par1,par2,tau,seed,n,denom,u_int,v_int,w_gen,w01",
    ]
    for name, fam, rot, p1, p2, seed in WEIGHTED:
        b = bicop(fam, rot, p1, p2)
        x = b.sample(N_WEIGHTED, seeds=[seed])
        ru, rv = ranks(x[:, 0]), ranks(x[:, 1])
        rng = np.random.default_rng(seed + 1000)
        w_gen = np.maximum(1, np.rint(rng.beta(0.5, 0.5, N_WEIGHTED) * W_SCALE)).astype(np.int64)
        w01 = (rng.random(N_WEIGHTED) < 0.6).astype(np.int64)
        row = [name, fam, rot, repr(p1), "" if p2 is None else repr(p2), repr(float(b.tau)),
               seed, N_WEIGHTED, N_WEIGHTED + 1, ints(ru), ints(rv), ints(w_gen), ints(w01)]
        lines.append(",".join(str(c) for c in row))
        if name == "gaussian":
            lu = (TIE_LEVELS * ru) // (N_WEIGHTED + 1) + 1
            lv = (TIE_LEVELS * rv) // (N_WEIGHTED + 1) + 1
            row = ["gaussian_ties", fam, rot, repr(p1), "", repr(float(b.tau)), seed,
                   N_WEIGHTED, TIE_LEVELS + 1, ints(lu), ints(lv), ints(w_gen), ints(w01)]
            lines.append(",".join(str(c) for c in row))
    OUT_W.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_W.relative_to(ROOT)}: {len(WEIGHTED) + 1} data sets")

    lines = header("FR-11 selection-recovery data") + [
        "# u_i = i/(n+1), v_i = v_by_u[i]/(n+1): the v-rank of the point of u-rank i.",
        "# par2 is nu (student) or delta (bb1); tau: pyvinecopulib Bicop.tau of the parameters.",
        "dataset,family,rotation,par1,par2,tau,seed,n,v_by_u",
    ]
    for name, fam, rot, p1, p2 in SELECTION:
        b = bicop(fam, rot, p1, p2)
        for seed in SEEDS_SELECTION:
            x = b.sample(N_SELECTION, seeds=[seed])
            ru, rv = ranks(x[:, 0]), ranks(x[:, 1])
            v_by_u = np.empty(N_SELECTION, dtype=np.int64)
            v_by_u[ru - 1] = rv
            row = [name, fam, rot, repr(p1), "" if p2 is None else repr(p2),
                   repr(float(b.tau)), seed, N_SELECTION, ints(v_by_u)]
            lines.append(",".join(str(c) for c in row))
    OUT_S.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_S.relative_to(ROOT)}: {len(SELECTION)} families x "
          f"{len(SEEDS_SELECTION)} seeds, n = {N_SELECTION}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
